// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductCatalog.Infrastructure.Data;

#nullable disable

namespace ProductCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225023154_SeedInitial100Products")]
    partial class SeedInitial100Products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductCatalog.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+1",
                            Name = "Classic Toys Product 1",
                            Price = 122.97m,
                            Rating = 1,
                            StockQuantity = 261
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+2",
                            Name = "Deluxe Toys Product 2",
                            Price = 166.29m,
                            Rating = 2,
                            StockQuantity = 380
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+3",
                            Name = "Modern Sports Product 3",
                            Price = 352.87m,
                            Rating = 3,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+4",
                            Name = "Deluxe Food Product 4",
                            Price = 367.72m,
                            Rating = 1,
                            StockQuantity = 76
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+5",
                            Name = "Deluxe Food Product 5",
                            Price = 49.73m,
                            Rating = 1,
                            StockQuantity = 355
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+6",
                            Name = "Deluxe Toys Product 6",
                            Price = 177.74m,
                            Rating = 2,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+7",
                            Name = "Premium Food Product 7",
                            Price = 492.15m,
                            Rating = 4,
                            StockQuantity = 402
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+8",
                            Name = "Premium Clothing Product 8",
                            Price = 55.91m,
                            Rating = 4,
                            StockQuantity = 390
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+9",
                            Name = "Pro Clothing Product 9",
                            Price = 270.65m,
                            Rating = 1,
                            StockQuantity = 324
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+10",
                            Name = "Deluxe Sports Product 10",
                            Price = 55.72m,
                            Rating = 4,
                            StockQuantity = 210
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+11",
                            Name = "Premium Clothing Product 11",
                            Price = 338.65m,
                            Rating = 1,
                            StockQuantity = 133
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+12",
                            Name = "Vintage Electronics Product 12",
                            Price = 20.83m,
                            Rating = 3,
                            StockQuantity = 398
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+13",
                            Name = "Premium Home Product 13",
                            Price = 755.95m,
                            Rating = 1,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+14",
                            Name = "Premium Toys Product 14",
                            Price = 832.16m,
                            Rating = 3,
                            StockQuantity = 464
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+15",
                            Name = "Premium Sports Product 15",
                            Price = 345.49m,
                            Rating = 3,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+16",
                            Name = "Vintage Sports Product 16",
                            Price = 277.64m,
                            Rating = 3,
                            StockQuantity = 453
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+17",
                            Name = "Smart Electronics Product 17",
                            Price = 871.91m,
                            Rating = 4,
                            StockQuantity = 166
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+18",
                            Name = "Vintage Electronics Product 18",
                            Price = 309.92m,
                            Rating = 1,
                            StockQuantity = 388
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+19",
                            Name = "Deluxe Clothing Product 19",
                            Price = 471.56m,
                            Rating = 4,
                            StockQuantity = 493
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+20",
                            Name = "Modern Toys Product 20",
                            Price = 506.85m,
                            Rating = 4,
                            StockQuantity = 494
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+21",
                            Name = "Smart Books Product 21",
                            Price = 34.43m,
                            Rating = 2,
                            StockQuantity = 109
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+22",
                            Name = "Deluxe Clothing Product 22",
                            Price = 389.99m,
                            Rating = 5,
                            StockQuantity = 46
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+23",
                            Name = "Modern Electronics Product 23",
                            Price = 301.46m,
                            Rating = 5,
                            StockQuantity = 375
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+24",
                            Name = "Pro Electronics Product 24",
                            Price = 816.31m,
                            Rating = 5,
                            StockQuantity = 119
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+25",
                            Name = "Deluxe Books Product 25",
                            Price = 581.03m,
                            Rating = 1,
                            StockQuantity = 312
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+26",
                            Name = "Premium Clothing Product 26",
                            Price = 217.76m,
                            Rating = 5,
                            StockQuantity = 466
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+27",
                            Name = "Smart Clothing Product 27",
                            Price = 178.04m,
                            Rating = 3,
                            StockQuantity = 147
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+28",
                            Name = "Premium Toys Product 28",
                            Price = 548.36m,
                            Rating = 5,
                            StockQuantity = 195
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+29",
                            Name = "Smart Books Product 29",
                            Price = 427.28m,
                            Rating = 5,
                            StockQuantity = 271
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+30",
                            Name = "Premium Clothing Product 30",
                            Price = 12.56m,
                            Rating = 5,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+31",
                            Name = "Deluxe Home Product 31",
                            Price = 370.03m,
                            Rating = 5,
                            StockQuantity = 62
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+32",
                            Name = "Classic Beauty Product 32",
                            Price = 310.49m,
                            Rating = 4,
                            StockQuantity = 271
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+33",
                            Name = "Essential Food Product 33",
                            Price = 262.46m,
                            Rating = 3,
                            StockQuantity = 169
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+34",
                            Name = "Smart Clothing Product 34",
                            Price = 607.98m,
                            Rating = 2,
                            StockQuantity = 94
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+35",
                            Name = "Essential Food Product 35",
                            Price = 83.66m,
                            Rating = 5,
                            StockQuantity = 210
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+36",
                            Name = "Smart Food Product 36",
                            Price = 858.79m,
                            Rating = 5,
                            StockQuantity = 233
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+37",
                            Name = "Deluxe Clothing Product 37",
                            Price = 200.12m,
                            Rating = 3,
                            StockQuantity = 317
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+38",
                            Name = "Pro Electronics Product 38",
                            Price = 323.08m,
                            Rating = 4,
                            StockQuantity = 260
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+39",
                            Name = "Pro Sports Product 39",
                            Price = 533.57m,
                            Rating = 5,
                            StockQuantity = 99
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+40",
                            Name = "Classic Electronics Product 40",
                            Price = 292.30m,
                            Rating = 2,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 8, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+41",
                            Name = "Vintage Beauty Product 41",
                            Price = 340.74m,
                            Rating = 4,
                            StockQuantity = 226
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+42",
                            Name = "Modern Beauty Product 42",
                            Price = 780.90m,
                            Rating = 1,
                            StockQuantity = 155
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+43",
                            Name = "Deluxe Sports Product 43",
                            Price = 358.39m,
                            Rating = 1,
                            StockQuantity = 478
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+44",
                            Name = "Modern Beauty Product 44",
                            Price = 837.41m,
                            Rating = 5,
                            StockQuantity = 440
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+45",
                            Name = "Deluxe Books Product 45",
                            Price = 26.76m,
                            Rating = 3,
                            StockQuantity = 445
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+46",
                            Name = "Smart Toys Product 46",
                            Price = 276.58m,
                            Rating = 4,
                            StockQuantity = 470
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+47",
                            Name = "Essential Books Product 47",
                            Price = 48.33m,
                            Rating = 3,
                            StockQuantity = 342
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+48",
                            Name = "Classic Books Product 48",
                            Price = 554.62m,
                            Rating = 4,
                            StockQuantity = 321
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+49",
                            Name = "Premium Toys Product 49",
                            Price = 132.32m,
                            Rating = 2,
                            StockQuantity = 421
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+50",
                            Name = "Premium Books Product 50",
                            Price = 531.41m,
                            Rating = 1,
                            StockQuantity = 175
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+51",
                            Name = "Premium Toys Product 51",
                            Price = 860.32m,
                            Rating = 4,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+52",
                            Name = "Essential Toys Product 52",
                            Price = 784.56m,
                            Rating = 4,
                            StockQuantity = 178
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+53",
                            Name = "Classic Home Product 53",
                            Price = 721.47m,
                            Rating = 3,
                            StockQuantity = 277
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2024, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+54",
                            Name = "Essential Home Product 54",
                            Price = 887.27m,
                            Rating = 2,
                            StockQuantity = 348
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+55",
                            Name = "Pro Sports Product 55",
                            Price = 634.41m,
                            Rating = 3,
                            StockQuantity = 158
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+56",
                            Name = "Smart Home Product 56",
                            Price = 461.63m,
                            Rating = 1,
                            StockQuantity = 429
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+57",
                            Name = "Classic Home Product 57",
                            Price = 516.45m,
                            Rating = 1,
                            StockQuantity = 203
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+58",
                            Name = "Modern Home Product 58",
                            Price = 445.82m,
                            Rating = 3,
                            StockQuantity = 357
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+59",
                            Name = "Pro Clothing Product 59",
                            Price = 426.81m,
                            Rating = 5,
                            StockQuantity = 453
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+60",
                            Name = "Smart Clothing Product 60",
                            Price = 804.65m,
                            Rating = 4,
                            StockQuantity = 316
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2024, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+61",
                            Name = "Modern Sports Product 61",
                            Price = 66.89m,
                            Rating = 5,
                            StockQuantity = 54
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+62",
                            Name = "Deluxe Beauty Product 62",
                            Price = 148.59m,
                            Rating = 1,
                            StockQuantity = 188
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+63",
                            Name = "Premium Electronics Product 63",
                            Price = 597.58m,
                            Rating = 2,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+64",
                            Name = "Pro Food Product 64",
                            Price = 369.06m,
                            Rating = 1,
                            StockQuantity = 299
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+65",
                            Name = "Deluxe Books Product 65",
                            Price = 55.16m,
                            Rating = 4,
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+66",
                            Name = "Pro Sports Product 66",
                            Price = 481.44m,
                            Rating = 5,
                            StockQuantity = 359
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+67",
                            Name = "Modern Beauty Product 67",
                            Price = 373.83m,
                            Rating = 4,
                            StockQuantity = 429
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+68",
                            Name = "Pro Beauty Product 68",
                            Price = 606.43m,
                            Rating = 4,
                            StockQuantity = 44
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2024, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+69",
                            Name = "Classic Food Product 69",
                            Price = 650.63m,
                            Rating = 5,
                            StockQuantity = 483
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+70",
                            Name = "Smart Home Product 70",
                            Price = 186.16m,
                            Rating = 5,
                            StockQuantity = 135
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+71",
                            Name = "Smart Sports Product 71",
                            Price = 836.28m,
                            Rating = 5,
                            StockQuantity = 29
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+72",
                            Name = "Vintage Food Product 72",
                            Price = 103.44m,
                            Rating = 1,
                            StockQuantity = 487
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+73",
                            Name = "Smart Sports Product 73",
                            Price = 37.57m,
                            Rating = 4,
                            StockQuantity = 277
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+74",
                            Name = "Classic Clothing Product 74",
                            Price = 681.96m,
                            Rating = 1,
                            StockQuantity = 57
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+75",
                            Name = "Deluxe Home Product 75",
                            Price = 892.37m,
                            Rating = 2,
                            StockQuantity = 354
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+76",
                            Name = "Deluxe Home Product 76",
                            Price = 488.46m,
                            Rating = 2,
                            StockQuantity = 21
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+77",
                            Name = "Smart Beauty Product 77",
                            Price = 877.98m,
                            Rating = 2,
                            StockQuantity = 157
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+78",
                            Name = "Pro Food Product 78",
                            Price = 59.33m,
                            Rating = 3,
                            StockQuantity = 414
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+79",
                            Name = "Smart Food Product 79",
                            Price = 235.07m,
                            Rating = 1,
                            StockQuantity = 439
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+80",
                            Name = "Vintage Sports Product 80",
                            Price = 698.75m,
                            Rating = 4,
                            StockQuantity = 226
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2024, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+81",
                            Name = "Classic Books Product 81",
                            Price = 112.16m,
                            Rating = 3,
                            StockQuantity = 54
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2024, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+82",
                            Name = "Vintage Books Product 82",
                            Price = 626.50m,
                            Rating = 4,
                            StockQuantity = 76
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+83",
                            Name = "Pro Books Product 83",
                            Price = 874.04m,
                            Rating = 2,
                            StockQuantity = 169
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+84",
                            Name = "Deluxe Home Product 84",
                            Price = 109.12m,
                            Rating = 5,
                            StockQuantity = 71
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+85",
                            Name = "Deluxe Toys Product 85",
                            Price = 439.94m,
                            Rating = 3,
                            StockQuantity = 455
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+86",
                            Name = "Vintage Electronics Product 86",
                            Price = 193.70m,
                            Rating = 5,
                            StockQuantity = 340
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality books product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+87",
                            Name = "Essential Books Product 87",
                            Price = 350.24m,
                            Rating = 3,
                            StockQuantity = 270
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+88",
                            Name = "Essential Clothing Product 88",
                            Price = 246.35m,
                            Rating = 3,
                            StockQuantity = 237
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+89",
                            Name = "Modern Toys Product 89",
                            Price = 167.33m,
                            Rating = 1,
                            StockQuantity = 242
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality clothing product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+90",
                            Name = "Classic Clothing Product 90",
                            Price = 202.52m,
                            Rating = 2,
                            StockQuantity = 363
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+91",
                            Name = "Vintage Electronics Product 91",
                            Price = 44.53m,
                            Rating = 1,
                            StockQuantity = 430
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2024, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality sports product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+92",
                            Name = "Essential Sports Product 92",
                            Price = 789.74m,
                            Rating = 1,
                            StockQuantity = 430
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+93",
                            Name = "Pro Beauty Product 93",
                            Price = 78.94m,
                            Rating = 5,
                            StockQuantity = 62
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+94",
                            Name = "Modern Electronics Product 94",
                            Price = 80.67m,
                            Rating = 2,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality toys product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+95",
                            Name = "Essential Toys Product 95",
                            Price = 395.87m,
                            Rating = 3,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+96",
                            Name = "Deluxe Beauty Product 96",
                            Price = 330.71m,
                            Rating = 3,
                            StockQuantity = 243
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality beauty product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+97",
                            Name = "Modern Beauty Product 97",
                            Price = 538.30m,
                            Rating = 5,
                            StockQuantity = 54
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality home product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+98",
                            Name = "Pro Home Product 98",
                            Price = 218.34m,
                            Rating = 3,
                            StockQuantity = 305
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality electronics product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+99",
                            Name = "Premium Electronics Product 99",
                            Price = 221.52m,
                            Rating = 4,
                            StockQuantity = 458
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality food product with excellent features. Perfect for everyday use and special occasions.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Product+100",
                            Name = "Smart Food Product 100",
                            Price = 183.20m,
                            Rating = 2,
                            StockQuantity = 441
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
